export type ProductCategory =
  | "labiales"
  | "rostro"
  | "ojos"
  | "skincare"
  | "unas"
  | "capilar"

export interface Product {
  id: string
  name: string
  price: number
  category: ProductCategory
  description: string
  image: string
  variants?: string[]
  badge?: "nuevo" | "bestseller" | "oferta"
  imagePosition?: string
}

export const CATEGORIES: { id: ProductCategory; label: string; tagline: string }[] = [
  { id: "labiales",  label: "Labiales",       tagline: "Besos de seda y color" },
  { id: "rostro",    label: "Rostro",          tagline: "La base de tu belleza" },
  { id: "ojos",      label: "Ojos",            tagline: "Miradas que hipnotizan" },
  { id: "skincare",  label: "Skin Care",       tagline: "Tu ritual de reina" },
  { id: "unas",      label: "Uñas",            tagline: "Detalles que enamoran" },
  { id: "capilar",   label: "Línea Capilar",   tagline: "Cabello de reina" },
]

export const PRODUCTS: Product[] = [

  // ═══════════════ LABIALES ═══════════════
  {
    id: "lip-superstay-matte-ink",
    name: "Maybelline Superstay Matte Ink",
    price: 46000,
    category: "labiales",
    description: "Labial líquido mate de hasta 16 horas.",
    image: "/images/products/Maybelline Superstay Matte Ink.png",
    badge: "bestseller",
    variants: ["Dreamer", "Lover", "Pioneer", "Seductress", "Inspirer", "Mover", "Revolutionary", "Artist"],
  },
  {
    id: "lip-spiral-gloss-montoc",
    name: "Spiral Gloss Montoc",
    price: 24000,
    category: "labiales",
    description: "Gloss cremoso con acabado brillante.",
    image: "/images/products/Spiral Gloss Montoc.png",
    variants: ["Susu", "Yasu", "Tacey", "Kafu"],
  },
  {
    id: "lip-glowfusion-montoc",
    name: "GlowFusion Montoc",
    price: 25000,
    category: "labiales",
    description: "Gloss hidratante de larga duración.",
    image: "/images/products/GlowFusion Montoc.png",
    variants: ["Alba", "Lyra", "Ariel", "Aurora"],
    imagePosition: "70% 80%",
  },
  {
    id: "lip-vogue-resist-14h",
    name: "Labial Vogue Resist 14H",
    price: 23000,
    category: "labiales",
    description: "Labial líquido mate de larga duración.",
    image: "/images/products/Labial Vogue Resist 14H.png",
    variants: ["Elegante", "Fabulosa", "Encantadora", "Valiente", "Apasionada", "Atrevida"],
  },
  {
    id: "lip-gloss-atenea",
    name: "Lip Gloss Atenea 1stScene",
    price: 30000,
    category: "labiales",
    description: "Gloss brillante con efecto plumping.",
    image: "/images/products/Lip Gloss Atenea 1stScene.png",
    badge: "nuevo",
    variants: ["Coco", "Shell Coral", "Cool Ice", "Coral Haze", "Bright Pink"],
  },
  {
    id: "lip-feels-ruby-rose-mate",
    name: "Labial Líquido Mate Feels Ruby Rose",
    price: 11000,
    category: "labiales",
    description: "Acabado mate aterciopelado de larga duración.",
    image: "/images/products/Labial Liquido Mate Feels Ruby Rose.png",
    variants: ["129", "356", "362", "366", "376", "066"],
  },
  {
    id: "lip-duo-fells-ruby-rose",
    name: "Labial Duo Fells Ruby Rose",
    price: 12500,
    category: "labiales",
    description: "Labial en barra con acabado satinado.",
    image: "/images/products/Labial Duo Fells Ruby Rose.png",
    variants: ["312", "302", "316", "360", "311", "362", "361", "211"],
  },
  {
    id: "lip-3b-barra",
    name: "Labial en Barra 3b",
    price: 13000,
    category: "labiales",
    description: "Labial cremoso clásico.",
    image: "/images/products/Labial en Barra 3b Jmart.png",
    variants: ["Aventura", "Frutos Rojos", "Nude", "Pimienta", "Rosa", "Vital"],
  },
  {
    id: "lip-tinta-tatto-engol",
    name: "Tinta Lip Tatto Engol",
    price: 5000,
    category: "labiales",
    description: "Tinte buildable para un look natural y duradero.",
    image: "/images/products/Tinta Lip Tattoo Engol.png",
    variants: ["01", "02", "03", "04"],
  },
  {
    id: "lip-juicy-bomb-essence",
    name: "Brillo Labial Essence Juicy Bomb",
    price: 9000,
    category: "labiales",
    description: "Brillo jugoso con aroma afrutado.",
    image: "/images/products/Brillo Labial Essence Juicy Bomb.png",
    variants: ["Lovely", "Witty", "Proud", "Poppin"],
  },
  {
    id: "lip-nailen-mate",
    name: "Labial Mate Nailen en Barra",
    price: 10700,
    category: "labiales",
    description: "Labial en barra acabado mate.",
    image: "/images/products/Labial Mate Nailen en Barra.png",
    variants: ["Aventura", "Frutos Rojos", "Nude", "Pimienta", "Rosa", "Vital"],
  },
  {
    id: "lip-samy-mate",
    name: "Samy Labial Líquido Matte",
    price: 10800,
    category: "labiales",
    description: "Labial líquido mate de larga duración.",
    image: "/images/products/Samy Labial Liquido Matte.png",
    variants: ["01", "02", "03", "06", "08", "12", "15"],
  },
  {
    id: "lip-engol-highlighter",
    name: "Brillo Holográfico Engol",
    price: 5000,
    category: "labiales",
    description: "Gloss con destellos holográficos.",
    image: "/images/products/Brillo Holografico Engloss.png",
  },
  {
    id: "lip-lipgloss-engol",
    name: "Lipgloss Engol",
    price: 5000,
    category: "labiales",
    description: "Gloss transparente de larga duración.",
    image: "/images/products/Lipgloss Engol.png",
  },

  // ═══════════════ ROSTRO ═══════════════
  {
    id: "base-superstay-maybelline-24h",
    name: "Base Superstay Maybelline 24H",
    price: 60200,
    category: "rostro",
    description: "Cobertura total hasta 24 horas.",
    image: "/images/products/Base Superstay 24H Maybelline.png",
    badge: "bestseller",
    variants: ["Buff Beige", "Cassic Ivory", "Golden", "Honey", "Natural Beige", "IvoryPorcelain", "Sun Beige", "Toffe", "Warm Nude"],
  },
  {
    id: "base-fitme-maybelline-16h",
    name: "Base Fit Me Maybelline 16H",
    price: 48000,
    category: "rostro",
    description: "Base mate y sin poros, 16H.",
    image: "/images/products/Base Fit Me 16H Maybelline.png",
    badge: "bestseller",
    variants: ["Natural Ivory", "Buff Beige", "Soft Tan", "Natural Beige", "Porcelain", "Nude Beige", "Pure Beige", "Warm Honey"],
  },
  {
    id: "base-humide-montoc",
    name: "Base HUMIDE Montoc",
    price: 35000,
    category: "rostro",
    description: "Base hidratante de larga duración.",
    image: "/images/products/Base HUMIDE Montoc.png",
    variants: ["100", "200", "300", "400", "500", "600", "700"],
  },
  {
    id: "base-vogue-resist-24h",
    name: "Base Vogue Resist 24H",
    price: 29500,
    category: "rostro",
    description: "Cobertura media-alta 24H.",
    image: "/images/products/Base Vogue Resist 24H.png",
    variants: ["Capuccino", "Glamour", "Miel", "Natural", "Petalo"],
  },
  {
    id: "base-atenea-1stscene",
    name: "Base Atenea 1stScene",
    price: 45000,
    category: "rostro",
    description: "Base fluida acabado natural.",
    image: "/images/products/Base Atenea 1stScene.png",
    variants: ["Light", "Cream", "Vainilla", "Almond", "Sand"],
  },
  {
    id: "base-ultimate-detox-raquel",
    name: "Base Ultimate Detox Raquel",
    price: 25500,
    category: "rostro",
    description: "Base con detox de toxinas para piel más limpia.",
    image: "/images/products/Base Ultimate Detox Raquel.png",
  },
  {
    id: "corrector-maybelline-eraser",
    name: "Corrector Maybelline ERASER",
    price: 55000,
    category: "rostro",
    description: "Corrector antiojeras de alta cobertura.",
    image: "/images/products/Corrector Maybelline EASER.png",
    badge: "nuevo",
    variants: ["Ivory", "Medium", "Light", "Golden", "Honey"],
  },
  {
    id: "corrector-atenea-1stscene",
    name: "Corrector Atenea 1stScene",
    price: 30000,
    category: "rostro",
    description: "Corrector cremoso con vitamina C.",
    image: "/images/products/Corrector Atenea 1stScene.png",
  },
  {
    id: "corrector-bloomshell",
    name: "Corrector Blloomshell",
    price: 17500,
    category: "rostro",
    description: "Corrector con vitamina C y ácido hialurónico.",
    image: "/images/products/Corrector Blloomshell.png",
    variants: ["00", "01", "02", "03", "04", "05", "06", "07"],
  },
  {
    id: "polvo-suelto-montoc",
    name: "Polvo Suelto Montoc",
    price: 57000,
    category: "rostro",
    description: "Polvo suelto traslúcido fijador, efecto airbrush.",
    image: "/images/products/Polvo Suelto Montoc Soft Powder.png",
    variants: ["Polvo traslucido"],
  },
  {
    id: "polvo-suelto-raquel",
    name: "Polvo Suelto Raquel Minerals",
    price: 19000,
    category: "rostro",
    description: "Polvo suelto con minerales naturales.",
    image: "/images/products/Polvo Suelto Raquel Minerals.png",
    variants: ["Traslucido", "Banana", "Beige", "Miel", "Almendra"],
  },
  {
    id: "polvo-suelto-bloomshell",
    name: "Polvo Suelto Bloomshell",
    price: 36000,
    category: "rostro",
    description: "Polvo fijador ultraligero.",
    image: "/images/products/Polvo Suelto Bloomshell.png",
    variants: ["White", "Natural", "Pink"],
  },
  {
    id: "polvo-compacto-sppro",
    name: "Polvo Compacto SP PRO",
    price: 33600,
    category: "rostro",
    description: "Polvo compacto acabado sedoso.",
    image: "/images/products/Polvo Compacto SP PRO.png",
    variants: ["T00", "T01", "T02", "T03", "T04", "T05", "T06", "T09"],
  },
  {
    id: "polvo-compacto-nailen",
    name: "Polvo Compacto Nailen",
    price: 9800,
    category: "rostro",
    description: "Polvo compacto de larga duración.",
    image: "/images/products/Polvo Compacto Nailen.png",
    variants: ["1", "2", "3", "4", "5", "6", "7"],
  },
  {
    id: "polvo-compacto-raquel",
    name: "Polvo Compacto Raquel Piel de Oro",
    price: 19000,
    category: "rostro",
    description: "Polvo compacto con minerales naturales.",
    image: "/images/products/Polvo Compacto Raquel Piel de Oro.png",
  },
  {
    id: "polvo-compacto-smart-3b",
    name: "Polvo Compacto Smart 3b",
    price: 18000,
    category: "rostro",
    description: "Polvo compacto multifuncional.",
    image: "/images/products/Polvo Compacto Smart 3b.png",
  },
  {
    id: "polvo-compacto-fitme-maybelline",
    name: "Polvo Compacto FIT me Maybelline",
    price: 43000,
    category: "rostro",
    description: "Polvo compacto mate y sin poros.",
    image: "/images/products/Polvo Compacto FIT me Maybelline.png",
    badge: "bestseller",
  },
  {
    id: "rubor-1stscene",
    name: "Rubor Compacto 1ST SCENE",
    price: 37500,
    category: "rostro",
    description: "Rubor satinado de larga duración.",
    image: "/images/products/Rubor Compacto 1ST SCENE Atenea.png",
    badge: "nuevo",
    variants: ["Pink Pearl", "Peach Melba", "Dusty Rose", "Salmon"],
  },
  {
    id: "rubor-nostalgic-montoc",
    name: "Rubor en Crema Nostalgic Montoc",
    price: 30000,
    category: "rostro",
    description: "Rubor en crema fácil de difuminar.",
    image: "/images/products/Rubor en crema Nostalgic MONTOC.png",
    variants: ["So pretty", "Darling", "Exquisite", "Honey"],
  },
  {
    id: "rubor-humide-montoc",
    name: "Rubor Mont HUMIDE",
    price: 30000,
    category: "rostro",
    description: "Rubor en stick para mejillas naturales.",
    image: "/images/products/Rubor Mont HUMIDE Montoc.png",
    variants: ["Solé", "Rouse", "Dolce", "Sogno", "Luce"],
  },
  {
    id: "rubor-samy-blush",
    name: "Rubor Compacto Samy Blush",
    price: 6900,
    category: "rostro",
    description: "Rubor compacto de alta pigmentación.",
    image: "/images/products/Rubor Compacto Samy Blush.png",
    variants: ["Vanity", "Salmón", "Golden Rose", "Lady", "Satin Pink", "Tierra"],
  },
  {
    id: "rubor-nailen",
    name: "Rubor Nailen",
    price: 9800,
    category: "rostro",
    description: "Rubor compacto con acabado natural.",
    image: "/images/products/Rubor Nailen.png",
  },
  {
    id: "rubor-pocket-blush-montoc",
    name: "Rubor Pocket Blush Montoc",
    price: 28000,
    category: "rostro",
    description: "Rubor compacto mini para llevar siempre.",
    image: "/images/products/Rubor Pocket Blush Montoc.png",
  },
  {
    id: "rubor-jelly-blush-engol",
    name: "Jelly Blush Engol",
    price: 8500,
    category: "rostro",
    description: "Blush en gel de larga duración.",
    image: "/images/products/Jelly Blush Engol.png",
    variants: ["01", "02", "03", "04"],
  },
  {
    id: "contorno-liquido-montoc",
    name: "Contorno Líquido HUMIDE Montoc",
    price: 27000,
    category: "rostro",
    description: "Contorno líquido fácil de difuminar.",
    image: "/images/products/Contorno liquido HUMIDE Montoc.png",
    variants: ["Amber", "Toffe"],
  },
  {
    id: "iluminador-sppro-perla",
    name: "Polvo Iluminador SP PRO",
    price: 23000,
    category: "rostro",
    description: "Iluminador compacto de alta pigmentación.",
    image: "/images/products/Polvo Iluminador SP PRO Pro Pearl.png",
    variants: ["Bronce", "Perla"],
  },
  {
    id: "polvo-hadas-engol",
    name: "Polvo de Hadas Engol Highlighter",
    price: 8000,
    category: "rostro",
    description: "Highlighter en polvo con destellos suaves.",
    image: "/images/products/Polvo de Hadas Engol Highlighter.png",
  },
  {
    id: "fijador-montoc-dixy",
    name: "Fijador Maquillaje Montoc Dixy Fix",
    price: 28000,
    category: "rostro",
    description: "Spray fijador de maquillaje de larga duración.",
    image: "/images/products/Fijador Maquillaje Montoc Dixy Fix.png",
  },
  {
    id: "blender-sponge-montoc",
    name: "Blender Sponge Montoc",
    price: 20000,
    category: "rostro",
    description: "Esponja de maquillaje de alta densidad.",
    image: "/images/products/Blender Sponge LP018 Montoc.png",
    variants: ["LP018", "Beteada Morada"],
  },
  {
    id: "bronzer-hello-beach",
    name: "Bronzer Hello Beach Montoc",
    price: 25000,
    category: "rostro",
    description: "Bronzer en polvo para un tono sol natural.",
    image: "/images/products/Bronzer Hello Beach Montoc.png",
  },
  {
    id: "kit-brochas-montoc",
    name: "Kit Brochas Singolare V2 Montoc",
    price: 60000,
    category: "rostro",
    description: "Kit de brochas profesionales para maquillaje completo.",
    image: "/images/products/Kit Brochas Singolare V2 Montoc.png",
    badge: "nuevo",
  },

  // ═══════════════ OJOS ═══════════════
  {
    id: "mascara-skyhigh-maybelline",
    name: "Pestañina Sky High Maybelline",
    price: 61000,
    category: "ojos",
    description: "Máscara de volumen extremo para pestañas infinitas.",
    image: "/images/products/Pestanina Sky High Maybelline.png",
    badge: "bestseller",
  },
  {
    id: "mascara-colossal-maybelline",
    name: "Pestañina Maybelline COLOSSAL",
    price: 37000,
    category: "ojos",
    description: "Volumen x10 en una sola pasada.",
    image: "/images/products/Pestanina Maybelline COLOSSAL.png",
    variants: ["Volum Express Lavable", "Waterproof"],
  },
  {
    id: "mascara-essence-extreme",
    name: "Pestañinas Essence I♥EXTREME",
    price: 18000,
    category: "ojos",
    description: "Máscara de volumen y curvatura extrema.",
    image: "/images/products/Pestaninas Essence I Love Extreme.png",
    variants: ["Waterproof", "Volume", "Crazy Volume"],
  },
  {
    id: "mascara-vogue-larga",
    name: "Pestañinas Vogue Larga Duración",
    price: 23000,
    category: "ojos",
    description: "5 referencias para todo tipo de look.",
    image: "/images/products/Pestaninas Vogue Larga Duracion.png",
    variants: ["Efecto total 6", "Ultra Volumen", "Pestañas de muñeca", "Curvas perfectas", "Amor a primera vista"],
  },
  {
    id: "paleta-engol-42-tonos",
    name: "Paleta Sombras Engol Colombia Pro 42 tonos",
    price: 45000,
    category: "ojos",
    description: "42 sombras matte, shimmer y glitter.",
    image: "/images/products/Paleta Sombras Engol Colombia Pro Magica.png",
    badge: "bestseller",
  },
  {
    id: "paleta-ruby-rose-22-tonos",
    name: "Paleta Ruby Rose Amazing 22 tonos",
    price: 32000,
    category: "ojos",
    description: "22 sombras con primer incluido.",
    image: "/images/products/Paleta de Sombras Ruby Rose Amazing.png",
  },
  {
    id: "delineador-gel-montoc",
    name: "Delineador en Gel Montoc",
    price: 30000,
    category: "ojos",
    description: "Gel delineador negro intenso de larga duración.",
    image: "/images/products/Delineador en Gel Montoc.png",
    variants: ["Negro"],
  },
  {
    id: "delineador-bardot",
    name: "Delineador de Ojos Bardot",
    price: 10200,
    category: "ojos",
    description: "Lápiz delineador retráctil suave.",
    image: "/images/products/Delineador de ojos Bardot.png",
    variants: ["Beige", "Black"],
  },
  {
    id: "lapiz-nailen-retractil",
    name: "Lápiz Retráctil de Ojos Nailen",
    price: 9400,
    category: "ojos",
    description: "Delineador retráctil de larga duración.",
    image: "/images/products/Lapiz retractil de ojos Nailen.png",
    variants: ["Arabe", "Fiesta", "Latino", "Pasión", "Sangria", "Tahití"],
  },
  {
    id: "lapiz-delineador-cejas-ojos",
    name: "Lápiz Delineador Cejas y Ojos",
    price: 8000,
    category: "ojos",
    description: "Lápiz multifunción para cejas y ojos.",
    image: "/images/products/Lapiz Delineador Cejas y Ojos.png",
  },
  {
    id: "lapiz-cejas-doble-montoc",
    name: "Lápiz de Cejas Doble Montoc",
    price: 15000,
    category: "ojos",
    description: "Lápiz de cejas doble extremo con cepillo.",
    image: "/images/products/Lapiz de Cejas Doble Montoc HUMIDE.png",
    badge: "nuevo",
    variants: ["Medium", "Dark"],
  },
  {
    id: "tinta-cejas-vogue-resist",
    name: "Tinta Líquida de Cejas Vogue Resist",
    price: 19000,
    category: "ojos",
    description: "Tinta para cejas de hasta 24 horas.",
    image: "/images/products/Tinta Liquida De Cejas Vogue Resist.png",
    variants: ["Ivory", "Medium", "Light", "Golden", "Honey"],
  },
  {
    id: "pomada-cejas-engol",
    name: "Pomada de Cejas Engol",
    price: 4500,
    category: "ojos",
    description: "Pomada para cejas de larga duración.",
    image: "/images/products/Pomada de Cejas Engol Fashion.png",
    variants: ["Brown", "Brunette", "Chocolate"],
  },
  {
    id: "henna-cejas-moonlight",
    name: "Henna para Cejas Moonlight",
    price: 23000,
    category: "ojos",
    description: "Henna semipermanente para cejas naturales.",
    image: "/images/products/Henna para Cejas Moonlight.png",
    variants: ["Café Oscuro", "Café Medio"],
  },
  {
    id: "henna-cejas-perfectas",
    name: "Henna para Cejas Cejas Perfectas",
    price: 22000,
    category: "ojos",
    description: "Kit henna para cejas de larga duración.",
    image: "/images/products/Henna para Cejas Cejas Perfectas.png",
  },
  {
    id: "jabon-cejas-jbl",
    name: "Jabón de Cejas JBL Brow Soap",
    price: 12000,
    category: "ojos",
    description: "Jabón fijador para cejas definidas y peinadas.",
    image: "/images/products/Jabon de Cejas JBL Brow Soap.png",
  },
  {
    id: "perfilador-cejas-tinkle",
    name: "Perfilador de Cejas Tinkle",
    price: 9000,
    category: "ojos",
    description: "Cuchilla para dar forma precisa a las cejas.",
    image: "/images/products/Perfilador de Cejas Tinkle.png",
  },
  {
    id: "brochas-sombras-ojos",
    name: "Brochas para Sombras de Ojos",
    price: 15000,
    category: "ojos",
    description: "Set de brochas profesionales para ojos.",
    image: "/images/products/Brochas para Sombras de Ojos.png",
  },
  {
    id: "pestanas-most-beauty-3d",
    name: "Pestañas Enteras Most Beauty",
    price: 6000,
    category: "ojos",
    description: "Pestañas postizas reutilizables.",
    image: "/images/products/Pestanas Enteras Most Beauty 3D.png",
    variants: ["3D", "Daily 3D"],
  },
  {
    id: "pestanas-wonder-lashes",
    name: "Pestañas Most Beauty Wonder Lashes",
    price: 7000,
    category: "ojos",
    description: "Pestañas naturales de alta densidad.",
    image: "/images/products/Pestanas Most Beauty Wonder Lashes.png",
  },
  {
    id: "pestanas-belia-5d",
    name: "Pestañas Enteras Belia 5D",
    price: 7000,
    category: "ojos",
    description: "Pestañas de visón sintético 5D ultra naturales.",
    image: "/images/products/Pestanas Enteras Belia 5D Mei yan Er.png",
    variants: ["005", "047", "07", "2", "056", "055", "083"],
  },
  {
    id: "pestana-pelo-pelo-kickass",
    name: "Pestana Pelo a Pelo Kickass",
    price: 8000,
    category: "ojos",
    description: "Pestañas individuales para look natural.",
    image: "/images/products/Pestana Pelo a Pelo Kickass.png",
  },
  {
    id: "pegante-salon-pro",
    name: "Pegante De Pestanas Salon Pro",
    price: 18000,
    category: "ojos",
    description: "Adhesivo profesional para pestañas.",
    image: "/images/products/Pegante De Pestanas Salon Pro.png",
  },
  {
    id: "pegante-duo-pestanas",
    name: "Pegante para Pestañas Duo",
    price: 26000,
    category: "ojos",
    description: "Adhesivo profesional de larga duración.",
    image: "/images/products/Pegante para Pestanas Duo.png",
    variants: ["Dark", "White"],
  },

  // ═══════════════ SKINCARE ═══════════════
  {
    id: "gel-hidratante-montoc",
    name: "Gel Facial Hidratante Montoc",
    price: 52000,
    category: "skincare",
    description: "Gel facial hidratante de textura ligera para todo tipo de piel.",
    image: "/images/products/Gel Facial Hidratante Montoc Hydromo.png",
    badge: "bestseller",
  },
  {
    id: "protector-solar-loreal-fps50",
    name: "Protector Solar UV Defender FPS 50+ L'Oréal",
    price: 60900,
    category: "skincare",
    description: "Protector solar diario de amplio espectro.",
    image: "/images/products/Protector Solar UV Defender FPS50 Loreal.png",
    badge: "nuevo",
  },
  {
    id: "contorno-ojos-loreal",
    name: "Ácido Hialurónico Cuidado de Ojos L'Oréal",
    price: 60000,
    category: "skincare",
    description: "Hidrata, rellena y reduce líneas finas.",
    image: "/images/products/Acido Hialuronico Cuidado Ojos Loreal.png",
  },
  {
    id: "agua-micelar-garnier",
    name: "Agua Micelar Garnier",
    price: 37000,
    category: "skincare",
    description: "Desmaquillante micelar todo en 1.",
    image: "/images/products/Agua Micelar Garnier.png",
    variants: ["Todo en 1", "Vitamina C", "Ácido Salicílico"],
  },
  {
    id: "agua-micelar-vitu",
    name: "Vitú Agua Micelar Sábila y Pepino",
    price: 26000,
    category: "skincare",
    description: "Desmaquillante natural para pieles sensibles.",
    image: "/images/products/Vitu Agua Micelar Sabila y Pepino.png",
  },
  {
    id: "mascarilla-garnier",
    name: "Mascarillas en Tela Garnier",
    price: 11300,
    category: "skincare",
    description: "Mascarilla de tela en solo 15 minutos.",
    image: "/images/products/Mascarillas en Tela Garnier.png",
    variants: ["Vitamina C", "Hidra Bomb", "Pure Carbon"],
  },
  {
    id: "jabon-exfoliante-vitu",
    name: "Jabón Exfoliante Facial Vitú",
    price: 24000,
    category: "skincare",
    description: "Jabón exfoliante con frutas rojas.",
    image: "/images/products/Jabon Exfoliante Facial Vitu.png",
  },
  {
    id: "tonico-biofloral-raquel",
    name: "Tónico Biofloral Raquel",
    price: 19000,
    category: "skincare",
    description: "Tónico floral que equilibra y tonifica la piel.",
    image: "/images/products/Tonico Biofloral Raquel.png",
  },
  {
    id: "protector-nude-spf50",
    name: "Protector Solar Nude SPF50",
    price: 57500,
    category: "skincare",
    description: "Protector solar ligero de alta protección.",
    image: "/images/products/Protector Solar Nude SPF50.png",
    variants: ["Sin color", "Con color"],
  },
  {
    id: "protector-nude-spf100",
    name: "Protector Solar Nude SPF100 Sachet",
    price: 4000,
    category: "skincare",
    description: "Sachet de protector solar de máxima protección.",
    image: "/images/products/Protector Solar Nude SPF100 Sachet.png",
  },
  {
    id: "bronceador-solar-nude",
    name: "Bronceador Solar Nude Sachet",
    price: 4000,
    category: "skincare",
    description: "Bronceador solar en sachet para llevar.",
    image: "/images/products/Bronceador Solar Nude Sachet.png",
  },
  {
    id: "autobronceador-piel-oro",
    name: "Autobronceador Piel de Oro",
    price: 50000,
    category: "skincare",
    description: "Bronceado natural y duradero en spray.",
    image: "/images/products/Autobronceador Piel de Oro.png",
  },
  {
    id: "aceite-bronceador-piel-oro",
    name: "Aceite Bronceador Piel de Oro",
    price: 48000,
    category: "skincare",
    description: "Aceite bronceador que hidrata y potencia el bronceado.",
    image: "/images/products/Aceite Bronceador Piel de Oro.png",
  },
  {
    id: "aceite-antiestrias-piel-oro",
    name: "Aceite Antistrías Piel de Oro",
    price: 48000,
    category: "skincare",
    description: "Aceite nutritivo que previene y reduce estrías.",
    image: "/images/products/Aceite Antiestrias Piel de Oro.png",
  },
  {
    id: "crema-depilatoria-sedosa",
    name: "Crema Depilatoria Sedosa",
    price: 14000,
    category: "skincare",
    description: "Crema depilatoria hidratante para piernas y cuerpo.",
    image: "/images/products/Crema Depilatoria Sedosa.png",
  },
  {
    id: "sachet-crema-depilatoria",
    name: "Sachet Crema Depilatoria Lampina",
    price: 3000,
    category: "skincare",
    description: "Crema depilatoria en sachet para zonas pequeñas.",
    image: "/images/products/Sachet Crema Depilatoria Lampina.png",
  },
  {
    id: "gel-afeitar-barber",
    name: "Gel de Afeitar Barber Duvy Class",
    price: 15000,
    category: "skincare",
    description: "Gel de afeitar profesional para piel suave.",
    image: "/images/products/Gel de Afeitar Barber Duvy Class.png",
  },
  {
    id: "balsamo-after-shave",
    name: "Bálsamo After Shave Barber Duvy Class",
    price: 18000,
    category: "skincare",
    description: "Bálsamo calmante post-afeitado.",
    image: "/images/products/Balsamo After Shave Barber Duvy Class.png",
  },
  {
    id: "talco-barberia",
    name: "Talco Barbería Barber Duvy Class",
    price: 12000,
    category: "skincare",
    description: "Talco para barbería de uso profesional.",
    image: "/images/products/Talco Barberia Barber Duvy Class.png",
  },
  {
    id: "gel-vibrante-fawy-skin",
    name: "Gel Vibrante Fawy",
    price: 10800,
    category: "skincare",
    description: "Gel multifuncional con Vitamina E.",
    image: "/images/products/Gel Vibrante Fawy.png",
  },

  // ═══════════════ UÑAS ═══════════════
  {
    id: "esmalte-gel-polish-masglo",
    name: "Esmalte Gel Polish Semi Masglo",
    price: 22300,
    category: "unas",
    description: "Esmalte semipermanente de gel de larga duración.",
    image: "/images/products/Esmalte Gel Polish Semi Masglo.png",
    badge: "bestseller",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "esmalte-vogue-efecto-gel",
    name: "Esmalte Vogue Efecto Gel",
    price: 8200,
    category: "unas",
    description: "Esmalte con efecto gel de alta pigmentación.",
    image: "/images/products/Esmalte Vogue Efecto Gel.png",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "esmalte-masglo",
    name: "Esmalte Masglo",
    price: 9800,
    category: "unas",
    description: "Esmalte de alta cobertura y acabado brillante.",
    image: "/images/products/Esmalte Masglo.png",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "esmalte-admiss",
    name: "Esmalte Tradicional Admiss",
    price: 4000,
    category: "unas",
    description: "Esmalte clásico de larga duración.",
    image: "/images/products/Esmalte Tradicional Admiss.png",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "removedor-esmalte-lander",
    name: "Removedor de Esmalte Lander",
    price: 6600,
    category: "unas",
    description: "Removedor que cuida y fortalece la uña.",
    image: "/images/products/Removedor De Esmalte Lander.png",
    variants: ["Endurecedor", "Tradicional"],
  },
  {
    id: "removedor-samy-keratina",
    name: "Removedor de Esmalte con Keratina Samy",
    price: 15000,
    category: "unas",
    description: "Removedor con keratina para uñas sanas y fuertes.",
    image: "/images/products/Removedor de Esmalte Samy Keratin.png",
  },
  {
    id: "aceite-cuticula-brescia",
    name: "Aceite de Cutícula Brescia",
    price: 7000,
    category: "unas",
    description: "Aceite nutritivo que suaviza y cuida la cutícula.",
    image: "/images/products/Aceite de Cuticula Brescia.png",
  },
  {
    id: "removedor-cuticula-brescia",
    name: "Removedor de Cutícula Brescia",
    price: 8800,
    category: "unas",
    description: "Crema removedora de cutícula con Vitamina E.",
    image: "/images/products/Removedor de cuticula Brescia.png",
  },

  // ═══════════════ LÍNEA CAPILAR ═══════════════
  {
    id: "shampoo-acondicionador-liss-control",
    name: "Salon In Liss Control",
    price: 65400,
    category: "capilar",
    description: "Shampoo y acondicionador alisador profesional antifrizz. Valor unitario.",
    image: "/images/products/Shampoo y Acondicionador Salon In Liss Control.png",
    badge: "bestseller",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-acondicionador-hydra-repair",
    name: "Salon In Hydra Repair",
    price: 65400,
    category: "capilar",
    description: "Shampoo y acondicionador reparador para cabello dañado. Valor unitario.",
    image: "/images/products/Shampoo y Acondicionador Salon In Hydra Repair.png",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-acondicionador-glycolico",
    name: "Elvive Ácido Glicólico",
    price: 38000,
    category: "capilar",
    description: "Shampoo y acondicionador con ácido glicólico. Valor unitario.",
    image: "/images/products/Shampoo y Acondicionador Acido Glycolico Elvive.png",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-acondicionador-cebolla",
    name: "Versatil Cebolla",
    price: 28000,
    category: "capilar",
    description: "Shampoo y acondicionador anticaída con cebolla. Valor unitario.",
    image: "/images/products/Shampoo y Acondicionador Cebolla Versatil.png",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-acondicionador-equino",
    name: "Versatil Equino",
    price: 28000,
    category: "capilar",
    description: "Shampoo y acondicionador fortalecedor con proteínas equinas. Valor unitario.",
    image: "/images/products/Shampoo y Acondicionador Equino Versatil.png",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-acondicionador-color",
    name: "Versatil Protección Color",
    price: 28000,
    category: "capilar",
    description: "Shampoo y acondicionador protector de color. Valor unitario.",
    image: "/images/products/Shampoo y Acondicionador Proteccion Color Versatil.png",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-hialuronico-elvive",
    name: "Shampoo Hialurónico Elvive L'Oréal",
    price: 45000,
    category: "capilar",
    description: "Shampoo con ácido hialurónico para hidratación profunda.",
    image: "/images/products/Shampoo Hialuronico Elvive Loreal.png",
  },
  {
    id: "shampoo-absolut-repair-loreal",
    name: "Shampoo Absolut Repair L'Oréal Professionnel",
    price: 95000,
    category: "capilar",
    description: "Shampoo profesional de reparación intensa.",
    image: "/images/products/Shampoo Absolut Repair Loreal Profesional.png",
    badge: "nuevo",
  },
  {
    id: "shampoo-densificador-loreal",
    name: "Shampoo Densificador Serioxyl Advanced L'Oréal",
    price: 85000,
    category: "capilar",
    description: "Shampoo anticaída con tecnología densificadora.",
    image: "/images/products/Shampoo Densificador Serioxyl Advanced Loreal.png",
  },
  {
    id: "shampoo-control-caspa-versatil",
    name: "Shampoo 2 en 1 Control Caspa Versatil",
    price: 22000,
    category: "capilar",
    description: "Shampoo anticaspa 2 en 1 para uso diario.",
    image: "/images/products/Shampoo 2 en 1 Control Caspa Versatil.png",
  },
  {
    id: "shampoo-control-caspa-deep-roots",
    name: "Shampoo Control Caspa Deep Roots",
    price: 24000,
    category: "capilar",
    description: "Shampoo anticaspa de acción profunda.",
    image: "/images/products/Shampoo Control Caspa Deep Roots.png",
  },
  {
    id: "shampoo-control-caida-barber",
    name: "Shampoo Control Caída Barber Duvy Class",
    price: 20000,
    category: "capilar",
    description: "Shampoo anticaída para cabello masculino.",
    image: "/images/products/Shampoo Control Caida Barber Duvy Class.png",
  },
  {
    id: "shampoo-grasa-cebolla",
    name: "Shampoo Control Grasa Cebolla Fresh&Co",
    price: 22000,
    category: "capilar",
    description: "Shampoo para cabello graso con extracto de cebolla.",
    image: "/images/products/Shampoo Control Grasa Cebolla Fresh Co.png",
  },
  {
    id: "shampoo-color-freshco",
    name: "Shampoo Protección Color Fresh&Co",
    price: 22000,
    category: "capilar",
    description: "Shampoo para preservar el color del cabello teñido.",
    image: "/images/products/Shampoo Proteccion Color Fresh Co.png",
  },
  {
    id: "shampoo-nutritive-alfaparf",
    name: "Shampoo Nutritive Yellow Alfaparf",
    price: 55000,
    category: "capilar",
    description: "Shampoo nutritivo profesional Alfaparf.",
    image: "/images/products/Shampoo Nutritive Yellow Alfaparf.png",
  },
  {
    id: "shampoo-ponto-sachet",
    name: "Shampoo Ponto Sachet",
    price: 4000,
    category: "capilar",
    description: "Shampoo reparador en sachet.",
    image: "/images/products/Shampoo Ponto Sachet.png",
  },
  {
    id: "shampoo-cebolla-sachet",
    name: "Shampoo Cebolla Versatil Sachet",
    price: 3500,
    category: "capilar",
    description: "Shampoo anticaída con cebolla en sachet.",
    image: "/images/products/Shampoo Cebolla Versatil Sachet.png",
  },
  {
    id: "shampoo-vitamino-loreal",
    name: "Shampoo Vitamino Color L'Oréal",
    price: 80000,
    category: "capilar",
    description: "Shampoo protector de color con Omega 6.",
    image: "/images/products/Shampoo y Termo Protector Vitamino Color Loreal.png",
    variants: ["Shampoo", "Termo protector"],
  },
  {
    id: "acondicionador-keratin-salon-in",
    name: "Acondicionador Keratin Ultra Force Salon In",
    price: 52000,
    category: "capilar",
    description: "Acondicionador con keratina para cabello muy dañado.",
    image: "/images/products/Acondicionador Keratin Ultra Force Salon In.png",
  },
  {
    id: "acondicionador-liss-alfaparf",
    name: "Acondicionador Liss Yellow Alfaparf",
    price: 55000,
    category: "capilar",
    description: "Acondicionador alisador profesional Alfaparf.",
    image: "/images/products/Acondicionador Liss Yellow Alfaparf.png",
  },
  {
    id: "acondicionador-repair-alfaparf",
    name: "Acondicionador Repair Yellow Alfaparf",
    price: 55000,
    category: "capilar",
    description: "Acondicionador reparador profesional Alfaparf.",
    image: "/images/products/Acondicionador Repair Yellow Alfaparf.png",
  },
  {
    id: "tratamiento-metal-detox-loreal",
    name: "Tratamiento Metal Detox L'Oréal",
    price: 135000,
    category: "capilar",
    description: "Pre-tratamiento profesional que neutraliza metales y protege el cabello.",
    image: "/images/products/Tratamiento Metal Detox Loreal.png",
    badge: "nuevo",
  },
  {
    id: "cristal-liquido-alfaparf",
    name: "Cristal Líquido Sublime Semi Di Lino Alfaparf",
    price: 110000,
    category: "capilar",
    description: "Sérum de acabado cristalizado para brillo y suavidad extrema.",
    image: "/images/products/Cristal Liquido Sublime Semi Di Lino Alfaparf.png",
  },
  {
    id: "nikols-fitokeratina",
    name: "Nikols Tratamiento Fitokeratina",
    price: 20000,
    category: "capilar",
    description: "Tratamiento de keratina vegetal que sella la cutícula y da brillo.",
    image: "/images/products/Nikols Tratamiento Fitokeratina.png",
  },
  {
    id: "ampolletas-hair-saloon",
    name: "Ampolletas Capilares Hair Saloon Pluss",
    price: 8000,
    category: "capilar",
    description: "Ampolletas nutritivas de acción intensiva.",
    image: "/images/products/Ampolletas Capilares Hair Saloon Pluss.png",
  },
  {
    id: "ampolletas-alfaparf",
    name: "Ampolletas Capilares Alfaparf",
    price: 15000,
    category: "capilar",
    description: "Ampolletas de tratamiento profesional Alfaparf.",
    image: "/images/products/Ampolletas capilares Alfaparf.png",
  },
  {
    id: "deco-white-9-recamier",
    name: "Recamier Deco White 9 Sachet",
    price: 11300,
    category: "capilar",
    description: "Decolorante en sachet hasta 9 niveles de aclaramiento.",
    image: "/images/products/Recamier Deco White 9 Sachet.png",
  },
  {
    id: "deco-black-9-recamier",
    name: "Recamier Deco Black 9",
    price: 18000,
    category: "capilar",
    description: "Decolorante premium hasta 9 niveles.",
    image: "/images/products/Recamier Deco Black 9.png",
  },
  {
    id: "deco-alfapar-bb-bleach",
    name: "Decolorante Alfaparf BB BLEACH Sachet",
    price: 11000,
    category: "capilar",
    description: "Decolorante de alta performace, hasta 9 niveles High Lift.",
    image: "/images/products/Decolorante Alfaparf BB Bleach Sachet.png",
  },
  {
    id: "polvo-deco-plex-duvy",
    name: "Polvo Decolorante Plex Duvy Class",
    price: 18000,
    category: "capilar",
    description: "Decolorante en polvo con tecnología Plex.",
    image: "/images/products/Polvo Decolorante Plex Duvy Class.png",
  },
  {
    id: "agua-oxigenada-alfaparf",
    name: "Agua Oxigenada Óxido 10 Alfaparf",
    price: 14000,
    category: "capilar",
    description: "Agua oxigenada de 10 volúmenes para tintes.",
    image: "/images/products/Agua Oxigenada Oxido 10 Alfaparf.png",
  },
  {
    id: "agua-oxigenada-loreal",
    name: "L'Oréal Agua Oxigenada Majicreme 20",
    price: 16000,
    category: "capilar",
    description: "Oxidante cremoso 20 volúmenes L'Oréal.",
    image: "/images/products/Loreal Agua Oxigenada Majicreme 20.png",
  },
  {
    id: "oxy-cream-duvy",
    name: "Oxy Cream 20 Duvy Class",
    price: 14000,
    category: "capilar",
    description: "Crema oxidante 20 volúmenes.",
    image: "/images/products/Oxy Cream 20 Duvy Class.png",
  },
  {
    id: "tinte-casting-loreal",
    name: "Tinte Casting Sin Amoniaco L'Oréal",
    price: 42000,
    category: "capilar",
    description: "Tinte semipermanente sin amoniaco, brillo duradero.",
    image: "/images/products/Tinte Casting Sin Amoniaco Loreal.png",
  },
  {
    id: "tinte-colorwear-alfaparf",
    name: "Tinte Colorwear Sin Amoniaco Alfaparf",
    price: 45000,
    category: "capilar",
    description: "Tinte sin amoniaco profesional Alfaparf.",
    image: "/images/products/Tinte Colorwear Sin Amoniaco Alfaparf.png",
  },
  {
    id: "tinte-garnier",
    name: "Tinte Garnier Cor Intensa",
    price: 29000,
    category: "capilar",
    description: "Tinte de alta cobertura con aceites naturales.",
    image: "/images/products/Tinte Garnier Cor Intensa.png",
  },
  {
    id: "tinte-recamier-green-forest",
    name: "Tinte Recamier Green Forest Salon In",
    price: 32000,
    category: "capilar",
    description: "Tinte vegano con extractos naturales.",
    image: "/images/products/Tinte Recamier Green Forest Salon In.png",
  },
  {
    id: "tinte-recamier-techni-tone",
    name: "Tinte Recamier Techni Tone",
    price: 32000,
    category: "capilar",
    description: "Tinte profesional de larga duración.",
    image: "/images/products/Tinte Recamier Techni Tone.png",
  },
  {
    id: "tinte-deep-roots",
    name: "Tinte Tratamiento Deep Roots",
    price: 28000,
    category: "capilar",
    description: "Tinte con tratamiento nutritivo integrado.",
    image: "/images/products/Tinte Tratamiento Deep Roots.png",
  },
  {
    id: "tinte-vision-color-duvy",
    name: "Tinte Vision Color Duvy Class",
    price: 22000,
    category: "capilar",
    description: "Tinte profesional de alta cobertura.",
    image: "/images/products/Tinte Vision Color Duvy Class.png",
  },
  {
    id: "tinte-vision-touch",
    name: "Tinte Vision Touch Color",
    price: 22000,
    category: "capilar",
    description: "Tinte de larga duración con brillo intenso.",
    image: "/images/products/Tinte Vision Touch Color.png",
  },
  {
    id: "lissia-tinte-biotina",
    name: "Lissia Tinte Biotina Keratina",
    price: 28000,
    category: "capilar",
    description: "Tinte sin amoniaco con biotina y keratina.",
    image: "/images/products/Lissia Tinte en Crema Biotina Keratina.png",
  },
  {
    id: "cubre-canas-fresh-co",
    name: "Tratamiento Cubre Canas Fresh&Co",
    price: 26500,
    category: "capilar",
    description: "Cobertura de canas sin amoníaco ni peróxido.",
    image: "/images/products/Tratamiento Cubre Canas Fresh Co.png",
    variants: ["Castaño Oscuro"],
  },
  {
    id: "tratamiento-vegano-recamier",
    name: "Recamier Tratamiento Vegano Keratina y Colágeno",
    price: 38000,
    category: "capilar",
    description: "Tratamiento vegano intensivo con keratina y colágeno.",
    image: "/images/products/Recamier Tratamiento Vegano Keratina y Colageno.png",
  },
  {
    id: "tratamiento-amino-deep-roots",
    name: "Tratamiento Amino Keratina Deep Roots",
    price: 28000,
    category: "capilar",
    description: "Tratamiento con aminoácidos y keratina.",
    image: "/images/products/Tratamiento Amino Keratina Deep Roots.png",
  },
  {
    id: "tratamiento-bio-repair-deep-roots",
    name: "Tratamiento Bio Repair Deep Roots",
    price: 28000,
    category: "capilar",
    description: "Tratamiento reparador biológico.",
    image: "/images/products/Tratamiento Bio Repair Deep Roots.png",
  },
  {
    id: "tratamiento-bio-reparador-meicys",
    name: "Tratamiento Bio Reparador Argán Meicys",
    price: 30000,
    category: "capilar",
    description: "Tratamiento reparador con aceite de argán.",
    image: "/images/products/Tratamiento Bio Reparador Argan Meicys.png",
  },
  {
    id: "tratamiento-tinturado-deep-roots",
    name: "Tratamiento Cabello Tinturado Deep Roots",
    price: 28000,
    category: "capilar",
    description: "Tratamiento especial para cabello teñido.",
    image: "/images/products/Tratamiento Cabello Tinturado Deep Roots.png",
  },
  {
    id: "tratamiento-base-frutas",
    name: "Tratamiento Capilar Base de Frutas Deep Roots",
    price: 28000,
    category: "capilar",
    description: "Tratamiento nutritivo con base de frutas.",
    image: "/images/products/Tratamiento Capilar Base de Frutas Deep Roots.png",
  },
  {
    id: "tratamiento-color-salon-in",
    name: "Tratamiento Color Intensifier Salon In",
    price: 32000,
    category: "capilar",
    description: "Tratamiento que intensifica y protege el color.",
    image: "/images/products/Tratamiento Color Intensifier Salon In.png",
  },
  {
    id: "tratamiento-color-sachet",
    name: "Tratamiento Color Sachet Deep Roots",
    price: 5000,
    category: "capilar",
    description: "Tratamiento sachet para cabello teñido.",
    image: "/images/products/Tratamiento Color Sachet Deep Roots.png",
  },
  {
    id: "tratamiento-complex-freshco",
    name: "Tratamiento Complex Fresh&Co",
    price: 22000,
    category: "capilar",
    description: "Tratamiento capilar complejo revitalizante.",
    image: "/images/products/Tratamiento Complex Fresh Co.png",
  },
  {
    id: "tratamiento-embrion-pato",
    name: "Tratamiento Embrión de Pato Fresh&Co",
    price: 28000,
    category: "capilar",
    description: "Tratamiento regenerador con embrión de pato.",
    image: "/images/products/Tratamiento Embrion de Pato Fresh Co.png",
  },
  {
    id: "tratamiento-maracuya-skala",
    name: "Tratamiento Maracuyá Skala",
    price: 18000,
    category: "capilar",
    description: "Tratamiento nutritivo con maracuyá.",
    image: "/images/products/Tratamiento Maracuya Skala.png",
  },
  {
    id: "tratamiento-maxybelt-hialuronico",
    name: "Tratamiento Maxybelt Ácido Hialurónico",
    price: 35000,
    category: "capilar",
    description: "Tratamiento con ácido hialurónico para hidratación extrema.",
    image: "/images/products/Tratamiento Maxybelt Acido Hialuronico.png",
  },
  {
    id: "tratamiento-maxybelt-aminoacidos",
    name: "Tratamiento Maxybelt Aminoácidos",
    price: 35000,
    category: "capilar",
    description: "Tratamiento con aminoácidos para reparación estructural.",
    image: "/images/products/Tratamiento Maxybelt Aminoacidos.png",
  },
  {
    id: "tratamiento-romero-quina",
    name: "Tratamiento Romero y Quina Fresh&Co",
    price: 22000,
    category: "capilar",
    description: "Tratamiento anticaída con romero y quina.",
    image: "/images/products/Tratamiento Romero y Quina Fresh Co.png",
  },
  {
    id: "tratamiento-termoprotector-meicys",
    name: "Meicys Tratamiento Termoprotector",
    price: 28000,
    category: "capilar",
    description: "Termoprotector que protege hasta 230°C.",
    image: "/images/products/Meicys Tratamiento Termoprotector.png",
  },
  {
    id: "mascarilla-caviar-meicys",
    name: "Mascarilla Capilar Caviar Meicys",
    price: 35000,
    category: "capilar",
    description: "Mascarilla nutritiva con extracto de caviar.",
    image: "/images/products/Mascarilla Capilar Caviar Meicys.png",
  },
  {
    id: "laca-fijacion-alfaparf",
    name: "Laca Fijación Fuerte Yellow Alfaparf",
    price: 48000,
    category: "capilar",
    description: "Laca de fijación fuerte profesional Alfaparf.",
    image: "/images/products/Laca Fijacion Fuerte Yellow Alfaparf.png",
  },
  {
    id: "crema-peinar-mais-lisos",
    name: "Crema para Peinar Mais Lisos Skala",
    price: 16000,
    category: "capilar",
    description: "Crema alisadora para cabello con frizz.",
    image: "/images/products/Crema para Peinar Mais Lisos Skala.png",
  },
  {
    id: "crema-peinar-potato-amor",
    name: "Crema para Peinar Patato do Amor Skala",
    price: 16000,
    category: "capilar",
    description: "Crema para peinar con aceite de patata.",
    image: "/images/products/Crema para Peinar Potao do Amor Skala.png",
  },
  {
    id: "espuma-adapta-foam",
    name: "Espuma Adapta Foam Mousse Salon In",
    price: 38000,
    category: "capilar",
    description: "Mousse de fijación adaptable para todo tipo de cabello.",
    image: "/images/products/Espuma Adapta Foam Mousse Salon In.png",
  },
  {
    id: "encrespador-montoc-amore",
    name: "Encrespador Montoc Amore Curl",
    price: 32000,
    category: "capilar",
    description: "Definidor de rizos para cabello ondulado y rizado.",
    image: "/images/products/Encrespador Montoc Amore Curl.png",
  },
  {
    id: "cpc-12-meicys",
    name: "CPC 12 Reparación Anticaída Meicys",
    price: 38000,
    category: "capilar",
    description: "Tratamiento anticaída con 12 complejos activos.",
    image: "/images/products/CPC 12 Reparacion Anticaida Meicys.png",
  },
  {
    id: "tonico-anticaida-barber",
    name: "Tónico Control Caída Barber Duvy Class",
    price: 20000,
    category: "capilar",
    description: "Tónico anticaída para uso masculino.",
    image: "/images/products/Tonico Control Caida Barber Duvy Class.png",
  },
  {
    id: "kit-ponto-salvavidas",
    name: "Kit Ponto Salvavidas",
    price: 22000,
    category: "capilar",
    description: "Kit de recuperación intensiva para cabello muy dañado.",
    image: "/images/products/Kit Ponto Salvavidas.png",
  },
  {
    id: "cepillo-montoc-luna-pink",
    name: "Cepillo Cabello Montoc Luna Pink",
    price: 19000,
    category: "capilar",
    description: "Cepillo desenredante de alta calidad.",
    image: "/images/products/Cepillo Cabello Montoc Luna Pink.png",
    variants: ["Coral", "Rosa pastel"],
  },
  {
    id: "kanekalon-queen",
    name: "Kanekalon Queen",
    price: 25000,
    category: "capilar",
    description: "Extensiones de cabello sintético premium.",
    image: "/images/products/Kanekalon Queen.png",
  },
  {
    id: "kanekalon-soft-jumbo",
    name: "Kanekalon Soft Jumbo Bijoux",
    price: 28000,
    category: "capilar",
    description: "Extensiones jumbo de fibra suave.",
    image: "/images/products/Kanekalon Soft Jumbo Bijoux.png",
  },
  {
    id: "ganchos-cabello-enkor",
    name: "Ganchos para Cabello Enkor",
    price: 5000,
    category: "capilar",
    description: "Ganchos para cabello de alta durabilidad.",
    image: "/images/products/Ganchos para Cabello Enkor.png",
  },
  {
    id: "ligas-cabello-enkor",
    name: "Ligas para Cabello Enkor",
    price: 4000,
    category: "capilar",
    description: "Ligas elásticas para cabello sin daño.",
    image: "/images/products/Ligas para Cabello Enkor.png",
  },
  {
    id: "rulos-esponja-enkor",
    name: "Rulos Esponja Enkor",
    price: 12000,
    category: "capilar",
    description: "Rulos de esponja para rizos suaves sin calor.",
    image: "/images/products/Rulos Esponja Enkor.png",
  },
  {
    id: "rulos-tapa-enkor",
    name: "Rulos con Tapa Enkor",
    price: 15000,
    category: "capilar",
    description: "Rulos con tapa para mayor fijación del rizo.",
    image: "/images/products/Rulos con Tapa Enkor.png",
  },
  {
    id: "color-1-sachet",
    name: "Color 1 Sachet",
    price: 3500,
    category: "capilar",
    description: "Tinte en sachet para aplicación rápida.",
    image: "/images/products/Color 1 Sachet.png",
  },
]

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return PRODUCTS.filter((p) => p.category === cat)
}
