export type ProductCategory =
  | "labiales"
  | "rostro"
  | "ojos"
  | "skincare"
  | "unas"
  | "capilar"

export interface Product {
  id: string
  name: string
  price: number
  category: ProductCategory
  description: string
  image: string
  variants?: string[]
  badge?: "nuevo" | "bestseller" | "oferta"
}

export const CATEGORIES: { id: ProductCategory; label: string; tagline: string }[] = [
  { id: "labiales",  label: "Labiales",       tagline: "Besos de seda y color" },
  { id: "rostro",    label: "Rostro",          tagline: "La base de tu belleza" },
  { id: "ojos",      label: "Ojos",            tagline: "Miradas que hipnotizan" },
  { id: "skincare",  label: "Skin Care",       tagline: "Tu ritual de reina" },
  { id: "unas",      label: "Uñas",            tagline: "Detalles que enamoran" },
  { id: "capilar",   label: "Línea Capilar",   tagline: "Cabello de reina" },
]

export const PRODUCTS: Product[] = [

  // ═══════════════ LABIALES ═══════════════
  {
    id: "lip-superstay-matte-ink",
    name: "Maybelline Superstay Matte Ink",
    price: 46000,
    category: "labiales",
    description: "Labial líquido mate de hasta 16 horas.",
    image: "/images/products/lip-superstay-matte-ink.jpg",
    badge: "bestseller",
    variants: ["Dreamer", "Lover", "Pioneer", "Seductress", "Inspirer", "Mover", "Revolutionary", "Artist"],
  },
  {
    id: "lip-spiral-gloss-montoc",
    name: "Spiral Gloss Montoc",
    price: 24000,
    category: "labiales",
    description: "Gloss cremoso con acabado brillante.",
    image: "/images/products/lip-spiral-gloss-montoc.jpg",
    variants: ["Susu", "Yasu", "Tacey", "Kafu"],
  },
  {
    id: "lip-glowfusion-montoc",
    name: "GlowFusion Montoc",
    price: 25000,
    category: "labiales",
    description: "Gloss hidratante de larga duración.",
    image: "/images/products/lip-glowfusion-montoc.jpg",
    variants: ["Alba", "Lyra", "Ariel", "Aurora"],
  },
  {
    id: "lip-vogue-resist-14h",
    name: "Labial Vogue Resist 14H",
    price: 23000,
    category: "labiales",
    description: "Labial líquido mate de larga duración.",
    image: "/images/products/lip-vogue-resist-14h.jpg",
    variants: ["Elegante", "Fabulosa", "Encantadora", "Valiente", "Apasionada", "Atrevida"],
  },
  {
    id: "lip-gloss-atenea",
    name: "Lip Gloss Atenea 1stScene",
    price: 30000,
    category: "labiales",
    description: "Gloss brillante con efecto plumping.",
    image: "/images/products/lip-gloss-atenea.jpg",
    badge: "nuevo",
    variants: ["Coco", "Shell Coral", "Cool Ice", "Coral Haze", "Bright Pink"],
  },
  {
    id: "lip-feels-ruby-rose-mate",
    name: "Labial Líquido Mate Feels Ruby Rose",
    price: 11000,
    category: "labiales",
    description: "Acabado mate aterciopelado de larga duración.",
    image: "/images/products/lip-feels-ruby-rose-mate.jpg",
    variants: ["129", "356", "362", "366", "376", "066"],
  },
  {
    id: "lip-duo-fells-ruby-rose",
    name: "Labial Duo Fells Ruby Rose",
    price: 12500,
    category: "labiales",
    description: "Labial en barra con acabado satinado.",
    image: "/images/products/lip-duo-fells-ruby-rose.jpg",
    variants: ["312", "302", "316", "360", "311", "362", "361", "211"],
  },
  {
    id: "lip-3b-barra",
    name: "Labial en Barra 3b",
    price: 13000,
    category: "labiales",
    description: "Labial cremoso clásico.",
    image: "/images/products/lip-3b-barra.jpg",
    variants: ["Aventura", "Frutos Rojos", "Nude", "Pimienta", "Rosa", "Vital"],
  },
  {
    id: "lip-tinta-tatto-engol",
    name: "Tinta Lip Tatto Engol",
    price: 5000,
    category: "labiales",
    description: "Tinte buildable para un look natural y duradero.",
    image: "/images/products/lip-tinta-tatto-engol.jpg",
    variants: ["01", "02", "03", "04"],
  },
  {
    id: "lip-juicy-bomb-essence",
    name: "Brillo Labial Essence Juicy Bomb",
    price: 9000,
    category: "labiales",
    description: "Brillo jugoso con aroma afrutado.",
    image: "/images/products/lip-juicy-bomb-essence.jpg",
    variants: ["Lovely", "Witty", "Proud", "Poppin"],
  },
  {
    id: "lip-nailen-mate",
    name: "Labial Mate Nailen en Barra",
    price: 10700,
    category: "labiales",
    description: "Labial en barra acabado mate.",
    image: "/images/products/lip-nailen-mate.jpg",
    variants: ["Aventura", "Frutos Rojos", "Nude", "Pimienta", "Rosa", "Vital"],
  },
  {
    id: "lip-samy-mate",
    name: "Samy Labial Líquido Matte",
    price: 10800,
    category: "labiales",
    description: "Labial líquido mate de larga duración.",
    image: "/images/products/lip-samy-mate.jpg",
    variants: ["01", "02", "03", "06", "08", "12", "15"],
  },

  // ═══════════════ ROSTRO ═══════════════
  {
    id: "base-superstay-maybelline-24h",
    name: "Base Superstay Maybelline 24H",
    price: 60200,
    category: "rostro",
    description: "Cobertura total hasta 24 horas.",
    image: "/images/products/base-superstay-maybelline-24h.jpg",
    badge: "bestseller",
    variants: ["Buff Beige", "Cassic Ivory", "Golden", "Honey", "Natural Beige", "IvoryPorcelain", "Sun Beige", "Toffe", "Warm Nude"],
  },
  {
    id: "base-fitme-maybelline-16h",
    name: "Base Fit Me Maybelline 16H",
    price: 48000,
    category: "rostro",
    description: "Base mate y sin poros, 16H.",
    image: "/images/products/base-fitme-maybelline-16h.jpg",
    badge: "bestseller",
    variants: ["Natural Ivory", "Buff Beige", "Soft Tan", "Natural Beige", "Porcelain", "Nude Beige", "Pure Beige", "Warm Honey"],
  },
  {
    id: "base-humide-montoc",
    name: "Base HUMIDE Montoc",
    price: 35000,
    category: "rostro",
    description: "Base hidratante de larga duración.",
    image: "/images/products/base-humide-montoc.jpg",
    variants: ["100", "200", "300", "400", "500", "600", "700"],
  },
  {
    id: "base-vogue-resist-24h",
    name: "Base Vogue Resist 24H",
    price: 29500,
    category: "rostro",
    description: "Cobertura media-alta 24H.",
    image: "/images/products/base-vogue-resist-24h.jpg",
    variants: ["Capuccino", "Glamour", "Miel", "Natural", "Petalo"],
  },
  {
    id: "base-atenea-1stscene",
    name: "Base Atenea 1stScene",
    price: 45000,
    category: "rostro",
    description: "Base fluida acabado natural.",
    image: "/images/products/base-atenea-1stscene.jpg",
    variants: ["Light", "Cream", "Vainilla", "Almond", "Sand"],
  },
  {
    id: "corrector-maybelline-eraser",
    name: "Corrector Maybelline ERASER",
    price: 55000,
    category: "rostro",
    description: "Corrector antiojeras de alta cobertura.",
    image: "/images/products/corrector-maybelline-eraser.jpg",
    badge: "nuevo",
    variants: ["Ivory", "Medium", "Light", "Golden", "Honey"],
  },
  {
    id: "corrector-vogue-resist",
    name: "Corrector Vogue Resist",
    price: 18000,
    category: "rostro",
    description: "Corrector cremoso de larga duración.",
    image: "/images/products/corrector-vogue-resist.jpg",
    variants: ["Pétalo", "Natural", "Vainilla", "Canela"],
  },
  {
    id: "corrector-bloomshell",
    name: "Corrector Blloomshell",
    price: 17500,
    category: "rostro",
    description: "Corrector con vitamina C y ácido hialurónico.",
    image: "/images/products/corrector-bloomshell.jpg",
    variants: ["00", "01", "02", "03", "04", "05", "06", "07"],
  },
  {
    id: "polvo-suelto-montoc",
    name: "Polvo Suelto Montoc",
    price: 57000,
    category: "rostro",
    description: "Polvo suelto traslúcido fijador, efecto airbrush.",
    image: "/images/products/polvo-suelto-montoc.jpg",
    variants: ["Polvo traslucido"],
  },
  {
    id: "polvo-suelto-raquel",
    name: "Polvo Suelto Raquel Minerals",
    price: 19000,
    category: "rostro",
    description: "Polvo suelto con minerales naturales.",
    image: "/images/products/polvo-suelto-raquel.jpg",
    variants: ["Traslucido", "Banana", "Beige", "Miel", "Almendra"],
  },
  {
    id: "polvo-suelto-bloomshell",
    name: "Polvo Suelto Bloomshell",
    price: 36000,
    category: "rostro",
    description: "Polvo fijador ultraligero.",
    image: "/images/products/polvo-suelto-bloomshell.jpg",
    variants: ["White", "Natural", "Pink"],
  },
  {
    id: "polvo-compacto-sppro",
    name: "Polvo Compacto SP PRO",
    price: 33600,
    category: "rostro",
    description: "Polvo compacto acabado sedoso.",
    image: "/images/products/polvo-compacto-sppro.jpg",
    variants: ["T00", "T01", "T02", "T03", "T04", "T05", "T06", "T09"],
  },
  {
    id: "polvo-compacto-nailen",
    name: "Polvo Compacto Nailen",
    price: 9800,
    category: "rostro",
    description: "Polvo compacto de larga duración.",
    image: "/images/products/polvo-compacto-nailen.jpg",
    variants: ["1", "2", "3", "4", "5", "6", "7"],
  },
  {
    id: "rubor-1stscene",
    name: "Rubor Compacto 1ST SCENE",
    price: 37500,
    category: "rostro",
    description: "Rubor satinado de larga duración.",
    image: "/images/products/rubor-1stscene.jpg",
    badge: "nuevo",
    variants: ["Pink Pearl", "Peach Melba", "Dusty Rose", "Salmon"],
  },
  {
    id: "rubor-nostalgic-montoc",
    name: "Rubor en Crema Nostalgic Montoc",
    price: 30000,
    category: "rostro",
    description: "Rubor en crema fácil de difuminar.",
    image: "/images/products/rubor-nostalgic-montoc.jpg",
    variants: ["So pretty", "Darling", "Exquisite", "Honey"],
  },
  {
    id: "rubor-humide-montoc",
    name: "Rubor Mont HUMIDE",
    price: 30000,
    category: "rostro",
    description: "Rubor en stick para mejillas naturales.",
    image: "/images/products/rubor-humide-montoc.jpg",
    variants: ["Solé", "Rouse", "Dolce", "Sogno", "Luce"],
  },
  {
    id: "rubor-samy-blush",
    name: "Rubor Compacto Samy Blush",
    price: 6900,
    category: "rostro",
    description: "Rubor compacto de alta pigmentación.",
    image: "/images/products/rubor-samy-blush.jpg",
    variants: ["Vanity", "Salmón", "Golden Rose", "Lady", "Satin Pink", "Tierra"],
  },
  {
    id: "rubor-jelly-blush-engol",
    name: "Jelly Blush Engol",
    price: 8500,
    category: "rostro",
    description: "Blush en gel de larga duración.",
    image: "/images/products/rubor-jelly-blush-engol.jpg",
    variants: ["01", "02", "03", "04"],
  },
  {
    id: "contorno-liquido-montoc",
    name: "Contorno Líquido HUMIDE Montoc",
    price: 27000,
    category: "rostro",
    description: "Contorno líquido fácil de difuminar.",
    image: "/images/products/contorno-liquido-montoc.jpg",
    variants: ["Amber", "Toffe"],
  },
  {
    id: "iluminador-sppro-perla",
    name: "Polvo Iluminador SP PRO",
    price: 23000,
    category: "rostro",
    description: "Iluminador compacto de alta pigmentación.",
    image: "/images/products/iluminador-sppro-perla.jpg",
    variants: ["Bronce", "Perla"],
  },

  // ═══════════════ OJOS ═══════════════
  {
    id: "mascara-skyhigh-maybelline",
    name: "Pestañina Sky High Maybelline",
    price: 61000,
    category: "ojos",
    description: "Máscara de volumen extremo para pestañas infinitas.",
    image: "/images/products/mascara-skyhigh-maybelline.jpg",
    badge: "bestseller",
  },
  {
    id: "mascara-colossal-maybelline",
    name: "Pestañina Maybelline COLOSSAL",
    price: 37000,
    category: "ojos",
    description: "Volumen x10 en una sola pasada.",
    image: "/images/products/mascara-colossal-maybelline.jpg",
    variants: ["Volum Express Lavable", "Waterproof"],
  },
  {
    id: "mascara-essence-extreme",
    name: "Pestañinas Essence I♥EXTREME",
    price: 18000,
    category: "ojos",
    description: "Máscara de volumen y curvatura extrema.",
    image: "/images/products/mascara-essence-extreme.jpg",
    variants: ["Waterproof", "Volume", "Crazy Volume"],
  },
  {
    id: "mascara-vogue-larga",
    name: "Pestañinas Vogue Larga Duración",
    price: 23000,
    category: "ojos",
    description: "5 referencias para todo tipo de look.",
    image: "/images/products/mascara-vogue-larga.jpg",
    variants: ["Efecto total 6", "Ultra Volumen", "Pestañas de muñeca", "Curvas perfectas", "Amor a primera vista"],
  },
  {
    id: "paleta-engol-42-tonos",
    name: "Paleta Sombras Engol Colombia Pro 42 tonos",
    price: 45000,
    category: "ojos",
    description: "42 sombras matte, shimmer y glitter.",
    image: "/images/products/paleta-engol-42-tonos.jpg",
    badge: "bestseller",
  },
  {
    id: "paleta-ruby-rose-22-tonos",
    name: "Paleta Ruby Rose Amazing 22 tonos",
    price: 32000,
    category: "ojos",
    description: "22 sombras con primer incluido.",
    image: "/images/products/paleta-ruby-rose-22-tonos.jpg",
  },
  {
    id: "delineador-gel-montoc",
    name: "Delineador en Gel Montoc",
    price: 30000,
    category: "ojos",
    description: "Gel delineador negro intenso de larga duración.",
    image: "/images/products/delineador-gel-montoc.jpg",
    variants: ["Negro"],
  },
  {
    id: "delineador-bardot",
    name: "Delineador de Ojos Bardot",
    price: 10200,
    category: "ojos",
    description: "Lápiz delineador retráctil suave.",
    image: "/images/products/delineador-bardot.jpg",
    variants: ["Beige", "Black"],
  },
  {
    id: "lapiz-nailen-retractil",
    name: "Lápiz Retráctil de Ojos Nailen",
    price: 9400,
    category: "ojos",
    description: "Delineador retráctil de larga duración.",
    image: "/images/products/lapiz-nailen-retractil.jpg",
    variants: ["Arabe", "Fiesta", "Latino", "Pasión", "Sangria", "Tahití"],
  },
  {
    id: "lapiz-cejas-doble-montoc",
    name: "Lápiz de Cejas Doble Montoc",
    price: 15000,
    category: "ojos",
    description: "Lápiz de cejas doble extremo con cepillo.",
    image: "/images/products/lapiz-cejas-doble-montoc.jpg",
    badge: "nuevo",
    variants: ["Medium", "Dark"],
  },
  {
    id: "tinta-cejas-vogue-resist",
    name: "Tinta Líquida de Cejas Vogue Resist",
    price: 19000,
    category: "ojos",
    description: "Tinta para cejas de hasta 24 horas.",
    image: "/images/products/tinta-cejas-vogue-resist.jpg",
    variants: ["Ivory", "Medium", "Light", "Golden", "Honey"],
  },
  {
    id: "pomada-cejas-engol",
    name: "Pomada de Cejas Engol",
    price: 4500,
    category: "ojos",
    description: "Pomada para cejas de larga duración.",
    image: "/images/products/pomada-cejas-engol.jpg",
    variants: ["Brown", "Brunette", "Chocolate"],
  },
  {
    id: "henna-cejas-moonlight",
    name: "Henna para Cejas Moonlight",
    price: 23000,
    category: "ojos",
    description: "Henna semipermanente para cejas naturales.",
    image: "/images/products/henna-cejas-moonlight.jpg",
    variants: ["Café Oscuro", "Café Medio"],
  },
  {
    id: "pestanas-most-beauty-3d",
    name: "Pestañas Enteras Most Beauty",
    price: 6000,
    category: "ojos",
    description: "Pestañas postizas reutilizables.",
    image: "/images/products/pestanas-most-beauty-3d.jpg",
    variants: ["3D", "Daily 3D"],
  },
  {
    id: "pestanas-belia-5d",
    name: "Pestañas Enteras Belia 5D",
    price: 7000,
    category: "ojos",
    description: "Pestañas de visón sintético 5D ultra naturales.",
    image: "/images/products/pestanas-belia-5d.jpg",
    variants: ["005", "047", "07", "2", "056", "055", "083"],
  },
  {
    id: "pegante-duo-pestanas",
    name: "Pegante para Pestañas Duo",
    price: 26000,
    category: "ojos",
    description: "Adhesivo profesional de larga duración.",
    image: "/images/products/pegante-duo-pestanas.jpg",
    variants: ["Dark", "White"],
  },

  // ═══════════════ SKINCARE ═══════════════
  {
    id: "gel-hidratante-montoc",
    name: "Gel Facial Hidratante Montoc",
    price: 52000,
    category: "skincare",
    description: "Gel facial hidratante de textura ligera para todo tipo de piel.",
    image: "/images/products/gel-hidratante-montoc.jpg",
    badge: "bestseller",
  },
  {
    id: "protector-solar-loreal-fps50",
    name: "Protector Solar UV Defender FPS 50+ L'Oréal",
    price: 60900,
    category: "skincare",
    description: "Protector solar diario de amplio espectro.",
    image: "/images/products/protector-solar-loreal-fps50.jpg",
    badge: "nuevo",
  },
  {
    id: "contorno-ojos-loreal",
    name: "Ácido Hialurónico Cuidado de Ojos L'Oréal",
    price: 60000,
    category: "skincare",
    description: "Hidrata, rellena y reduce líneas finas.",
    image: "/images/products/contorno-ojos-loreal.jpg",
  },
  {
    id: "agua-micelar-garnier",
    name: "Agua Micelar Garnier",
    price: 37000,
    category: "skincare",
    description: "Desmaquillante micelar todo en 1.",
    image: "/images/products/agua-micelar-garnier.jpg",
    variants: ["Todo en 1", "Vitamina C", "Ácido Salicílico"],
  },
  {
    id: "agua-micelar-vitu",
    name: "Vitú Agua Micelar Sábila y Pepino",
    price: 26000,
    category: "skincare",
    description: "Desmaquillante natural para pieles sensibles.",
    image: "/images/products/agua-micelar-vitu.jpg",
  },
  {
    id: "mascarilla-garnier",
    name: "Mascarillas en Tela Garnier",
    price: 11300,
    category: "skincare",
    description: "Mascarilla de tela en solo 15 minutos.",
    image: "/images/products/mascarilla-garnier.jpg",
    variants: ["Vitamina C", "Hidra Bomb", "Pure Carbon"],
  },
  {
    id: "jabon-exfoliante-vitu",
    name: "Jabón Exfoliante Facial Vitú",
    price: 24000,
    category: "skincare",
    description: "Jabón exfoliante con frutas rojas.",
    image: "/images/products/jabon-exfoliante-vitu.jpg",
  },
  {
    id: "tonico-biofloral-raquel",
    name: "Tónico Biofloral Raquel",
    price: 19000,
    category: "skincare",
    description: "Tónico floral que equilibra y tonifica la piel.",
    image: "/images/products/tonico-biofloral-raquel.jpg",
  },
  {
    id: "protector-nude-spf50",
    name: "Protector Solar Nude SPF50",
    price: 57500,
    category: "skincare",
    description: "Protector solar ligero de alta protección.",
    image: "/images/products/protector-nude-spf50.jpg",
    variants: ["Sin color", "Con color"],
  },
  {
    id: "autobronceador-piel-oro",
    name: "Autobronceador Piel de Oro",
    price: 50000,
    category: "skincare",
    description: "Bronceado natural y duradero en spray.",
    image: "/images/products/autobronceador-piel-oro.jpg",
  },
  {
    id: "crema-depilatoria-sedosa",
    name: "Crema Depilatoria Sedosa",
    price: 14000,
    category: "skincare",
    description: "Crema depilatoria hidratante para piernas y cuerpo.",
    image: "/images/products/crema-depilatoria-sedosa.jpg",
  },

  // ═══════════════ UÑAS ═══════════════
  {
    id: "esmalte-gel-polish-masglo",
    name: "Esmalte Gel Polish Semi Masglo",
    price: 22300,
    category: "unas",
    description: "Esmalte semipermanente de gel de larga duración.",
    image: "/images/products/esmalte-gel-polish-masglo.jpg",
    badge: "bestseller",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "esmalte-vogue-efecto-gel",
    name: "Esmalte Vogue Efecto Gel",
    price: 8200,
    category: "unas",
    description: "Esmalte con efecto gel de alta pigmentación.",
    image: "/images/products/esmalte-vogue-efecto-gel.jpg",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "esmalte-masglo",
    name: "Esmalte Masglo",
    price: 9800,
    category: "unas",
    description: "Esmalte de alta cobertura y acabado brillante.",
    image: "/images/products/esmalte-masglo.jpg",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "esmalte-admiss",
    name: "Esmalte Tradicional Admiss",
    price: 4000,
    category: "unas",
    description: "Esmalte clásico de larga duración.",
    image: "/images/products/esmalte-admiss.jpg",
    variants: ["+20 tonos disponibles — consultar en tienda"],
  },
  {
    id: "removedor-esmalte-lander",
    name: "Removedor de Esmalte Lander",
    price: 6600,
    category: "unas",
    description: "Removedor que cuida y fortalece la uña.",
    image: "/images/products/removedor-esmalte-lander.jpg",
    variants: ["Endurecedor", "Tradicional"],
  },
  {
    id: "removedor-samy-keratina",
    name: "Removedor de Esmalte con Keratina Samy",
    price: 15000,
    category: "unas",
    description: "Removedor con keratina para uñas sanas y fuertes.",
    image: "/images/products/removedor-samy-keratina.jpg",
  },
  {
    id: "aceite-cuticula-brescia",
    name: "Aceite de Cutícula Brescia",
    price: 7000,
    category: "unas",
    description: "Aceite nutritivo que suaviza y cuida la cutícula.",
    image: "/images/products/aceite-cuticula-brescia.jpg",
  },
  {
    id: "removedor-cuticula-brescia",
    name: "Removedor de Cutícula Brescia",
    price: 8800,
    category: "unas",
    description: "Crema removedora de cutícula con Vitamina E.",
    image: "/images/products/removedor-cuticula-brescia.jpg",
  },

  // ═══════════════ LÍNEA CAPILAR ═══════════════
  {
    id: "shampoo-acondicionador-liss-control",
    name: "Recamier Salon In Liss Control",
    price: 65400,
    category: "capilar",
    description: "Shampoo y acondicionador alisador profesional antifrizz. Valor unitario.",
    image: "/images/products/shampoo-acondicionador-liss-control.jpg",
    badge: "bestseller",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "shampoo-acondicionador-hydra-repair",
    name: "Recamier Salon In Hydra Repair",
    price: 65400,
    category: "capilar",
    description: "Shampoo y acondicionador reparador para cabello dañado. Valor unitario.",
    image: "/images/products/shampoo-acondicionador-hydra-repair.jpg",
    variants: ["Shampoo", "Acondicionador"],
  },
  {
    id: "tratamiento-metal-detox-loreal",
    name: "Tratamiento Metal Detox L'Oréal",
    price: 135000,
    category: "capilar",
    description: "Pre-tratamiento profesional que neutraliza metales y protege el cabello.",
    image: "/images/products/tratamiento-metal-detox-loreal.jpg",
    badge: "nuevo",
  },
  {
    id: "cristal-liquido-alfaparf",
    name: "Cristal Líquido Sublime Semi Di Lino Alfaparf",
    price: 110000,
    category: "capilar",
    description: "Sérum de acabado cristalizado para brillo y suavidad extrema.",
    image: "/images/products/cristal-liquido-alfaparf.jpg",
  },
  {
    id: "nikols-fitokeratina",
    name: "Nikols Tratamiento Fitokeratina",
    price: 20000,
    category: "capilar",
    description: "Tratamiento de keratina vegetal que sella la cutícula y da brillo.",
    image: "/images/products/nikols-fitokeratina.jpg",
  },
  {
    id: "deco-white-9-recamier",
    name: "Recamier Deco White 9 Sachet",
    price: 11300,
    category: "capilar",
    description: "Decolorante en sachet hasta 9 niveles de aclaramiento.",
    image: "/images/products/deco-white-9-recamier.jpg",
  },
  {
    id: "deco-alfapar-bb-bleach",
    name: "Decolorante Alfapar BB BLEACH Sachet",
    price: 11000,
    category: "capilar",
    description: "Decolorante de alta performace, hasta 9 niveles High Lift.",
    image: "/images/products/deco-alfapar-bb-bleach.jpg",
  },
  {
    id: "cubre-canas-fresh-co",
    name: "Tratamiento Cubre Canas Fresh&Co",
    price: 26500,
    category: "capilar",
    description: "Cobertura de canas sin amoníaco ni peróxido.",
    image: "/images/products/cubre-canas-fresh-co.jpg",
    variants: ["Castaño Oscuro"],
  },
  {
    id: "kit-ponto-salvavidas",
    name: "Kit Ponto Salvavidas",
    price: 22000,
    category: "capilar",
    description: "Kit de recuperación intensiva para cabello muy dañado.",
    image: "/images/products/kit-ponto-salvavidas.jpg",
  },
  {
    id: "cepillo-montoc-luna-pink",
    name: "Cepillo Cabello Montoc Luna Pink",
    price: 19000,
    category: "capilar",
    description: "Cepillo desenredante de alta calidad.",
    image: "/images/products/cepillo-montoc-luna-pink.jpg",
    variants: ["Coral", "Rosa pastel"],
  },
  {
    id: "gel-vibrante-fawy",
    name: "Gel Vibrante Fawy",
    price: 10800,
    category: "capilar",
    description: "Gel de fijación fuerte con Vitamina E.",
    image: "/images/products/gel-vibrante-fawy.jpg",
  },
]

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return PRODUCTS.filter((p) => p.category === cat)
}
